### ISSUE TITLE
Minecraft Crash Report

### ISSUE THREAD

**Issue by ziceptor** [CubeEngine/core#54]
https://gist.github.com/ziceptor/981412996b6296fc2d25c1bac441f5dd

forge-1.12.2-14.23.0.2529-universal.jar
spongeforge-1.12.2-2529-7.0.0-BETA-2748.jar
LibCube.jar 1.0.0 Dev

**Comment by Faithcaio** [comment]
Yeah last SpongeAPI Version hat a breaking change with Enchantments.
Got it fixed already. Just need to release the new versions...

**Comment by ziceptor** [comment]
Yes, I see. Thank you!
