### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ziceptor** [CubeEngine/core#55]
https://gist.github.com/ziceptor/53c6c27f9305597b6439f0d93badbe4d

forge-1.12.2-14.23.0.2529-universal.jar
spongeforge-1.12.2-2529-7.0.0-BETA-2748.jar
LibCube.jar 1.0.1 dev

**Comment by Faithcaio** [comment]
You're not using 1.0.1 of libcube
https://gist.github.com/ziceptor/53c6c27f9305597b6439f0d93badbe4d#file-gistfile1-txt-L191

**Comment by ziceptor** [comment]
Maybe you have the wrong version posted Ore

**Comment by ziceptor** [comment]
1.0.1
1.0.0
identical

**Comment by Faithcaio** [comment]
Weird. I reuploaded. Try again

**Comment by ziceptor** [comment]
Works. Now swears on the itemduct. Maybe too old version? Add to the names of the plugins version. It will be easier to track bugs.

**Comment by Faithcaio** [comment]
reuploaded it too
