### ISSUE TITLE
CubeEngine did not load at all

### ISSUE THREAD

**Issue by ShunL12324** [CubeEngine/core#61]
Using latest SpongeForge build: 
    Minecraft: 1.16.5
    SpongeAPI: 8.0.0
    Sponge: 8.0.0
    SpongeForge: 1.16.5-36.2.5-8.0.0-RC1074
    JVM: 11.0.14/64-bit (Microsoft)
    OS: Windows Server 2022/10.0 (amd64)

plugins installed: Luckperms 5.4.4, crafteco 1.1, LibCube and teleport, travel (all are the latest version I can get from Ore)

the error: https://gist.github.com/Eric-liucn/1252d95777d1262772fe6452d66fb6a7

full log: https://gist.github.com/Eric-liucn/b2194b51b87ff7adea70c351a21d8f78

**Comment by pschichtel** [comment]
not sure if the API 8 versions are being published to ore yet, I remember there being issues with the ore upload.

@Faithcaio ?

**Comment by Faithcaio** [comment]
This happens on windows environments. I think i've got a fix.

@Eric-liucn do you mind trying out this version:

https://maven.cubyte.org/repository/snapshots/org/cubeengine/libcube/2.0.1-SNAPSHOT/libcube-2.0.1-20220217.200050-1.jar

If it works for you i'll also publish it on ore.

**Comment by ShunL12324** [comment]
@Faithcaio 
Had try this version but it crash the server
full log is here: https://gist.github.com/Eric-liucn/a0921cc0f2bdf823a94e01bbd37c317e

**Comment by Faithcaio** [comment]
oopsie wrong link we need the version including dependencies:

https://maven.cubyte.org/repository/snapshots/org/cubeengine/libcube/2.0.1-SNAPSHOT/libcube-2.0.1-20220217.200050-1-full.jar

**Comment by ShunL12324** [comment]
The plugin loaded! but there is still an error
Error: https://gist.github.com/Eric-liucn/d49696ef3f0b1f7df2481f84785e0acf
Full log (no other error related to cubeengine): https://gist.github.com/Eric-liucn/e89931feb4c9439403d77cbbcb178525

**Comment by Faithcaio** [comment]
Sadly that looks like its not a CubeEngine issue. 
Seems SpongeForge is not implementing `Optional<URI> locateResource(URI relative)` on its PluginContainers.

**Comment by Faithcaio** [comment]
try latest SpongeForge when its done building should be RC1077

**Comment by ShunL12324** [comment]
the plugin seems to work properly, I installed the teleport & travel module and I can use their commands  
But another error throws out, does it matter?
Error: https://gist.github.com/Eric-liucn/cd2819d6ea828f111f95d593aa744e26  
Full log: https://gist.github.com/Eric-liucn/8df55867493ecc267130fca0c1e08256  

Thanks for your help!

**Comment by Faithcaio** [comment]
It only matters for translations so not at all when using english. 
I'll have to fix that too but you can ignore it safely.

Notes;

https://github.com/CubeEngine/core/blob/api-8/src/main/java/org/cubeengine/libcube/service/i18n/I18n.java#L186
In Forge env. langs is "modjar://..."
